// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/common.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pager struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalRows            int64    `protobuf:"varint,3,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pager) Reset()         { *m = Pager{} }
func (m *Pager) String() string { return proto.CompactTextString(m) }
func (*Pager) ProtoMessage()    {}
func (*Pager) Descriptor() ([]byte, []int) {
	return fileDescriptor_1747d3070a2311a0, []int{0}
}

func (m *Pager) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pager.Unmarshal(m, b)
}
func (m *Pager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pager.Marshal(b, m, deterministic)
}
func (m *Pager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pager.Merge(m, src)
}
func (m *Pager) XXX_Size() int {
	return xxx_messageInfo_Pager.Size(m)
}
func (m *Pager) XXX_DiscardUnknown() {
	xxx_messageInfo_Pager.DiscardUnknown(m)
}

var xxx_messageInfo_Pager proto.InternalMessageInfo

func (m *Pager) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Pager) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Pager) GetTotalRows() int64 {
	if m != nil {
		return m.TotalRows
	}
	return 0
}

type Error struct {
	Code                 int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Detail               *anypb.Any `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_1747d3070a2311a0, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetDetail() *anypb.Any {
	if m != nil {
		return m.Detail
	}
	return nil
}

func init() {
	proto.RegisterType((*Pager)(nil), "proto.Pager")
	proto.RegisterType((*Error)(nil), "proto.Error")
}

func init() { proto.RegisterFile("proto/common.proto", fileDescriptor_1747d3070a2311a0) }

var fileDescriptor_1747d3070a2311a0 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x59, 0xd7, 0xac, 0xdb, 0xf1, 0x36, 0x78, 0x88, 0x8a, 0x20, 0x7b, 0xf2, 0x20, 0x09,
	0xe8, 0xd1, 0x93, 0x82, 0x77, 0x89, 0x07, 0xc1, 0xcb, 0x12, 0xdb, 0x18, 0x0a, 0x6d, 0xa7, 0x24,
	0x91, 0xd2, 0xfe, 0x7a, 0xc9, 0x64, 0x7b, 0x7a, 0xf3, 0xe6, 0x0d, 0xdf, 0x3c, 0xc0, 0x31, 0x50,
	0x22, 0x5d, 0x53, 0xdf, 0xd3, 0xa0, 0xd8, 0xa0, 0x60, 0xb9, 0xb9, 0xf6, 0x44, 0xbe, 0x73, 0x9a,
	0xdd, 0xcf, 0xdf, 0xaf, 0xb6, 0xc3, 0x5c, 0x2e, 0x0e, 0x5f, 0x20, 0x3e, 0xac, 0x77, 0x01, 0x11,
	0xce, 0x47, 0xeb, 0x9d, 0xdc, 0xdc, 0x6f, 0x1e, 0xb6, 0x86, 0x67, 0xbc, 0x85, 0x2a, 0xeb, 0x31,
	0xb6, 0x8b, 0x93, 0x67, 0x1c, 0xec, 0xf3, 0xe2, 0xb3, 0x5d, 0x1c, 0xde, 0x01, 0x24, 0x4a, 0xb6,
	0x3b, 0x06, 0x9a, 0xa2, 0xdc, 0x72, 0x5a, 0xf1, 0xc6, 0xd0, 0x14, 0x0f, 0x35, 0x88, 0xf7, 0x10,
	0x88, 0xc1, 0x35, 0x35, 0x05, 0x2c, 0x0c, 0xcf, 0x28, 0xe1, 0xa2, 0x77, 0x31, 0xe6, 0x7f, 0x19,
	0x5b, 0x99, 0xd5, 0xe2, 0x23, 0xec, 0x1a, 0x97, 0x6c, 0xdb, 0x31, 0xf1, 0xf2, 0xe9, 0x4a, 0x95,
	0xee, 0x6a, 0xed, 0xae, 0x5e, 0x87, 0xd9, 0x9c, 0x6e, 0xde, 0xe0, 0x7b, 0xaf, 0xf4, 0x4b, 0x89,
	0x76, 0x2c, 0xcf, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x63, 0x48, 0xf9, 0x89, 0x08, 0x01, 0x00,
	0x00,
}
